### ISSUE TITLE
hi, could a description of what the compatilbility option of Jumper component be added?

### ISSUE THREAD

**Issue by saufall** [Gitjas/Ascalons_Questpack#10]
i think it might be necessary for people to know why is there such an option and typically when to choose it over the original one,
"
-The component Jumper has a second install option that places Ugh and Jumper outside the cave (for compatibility with The Artisan's Shadow Magic mod)."
googling gives me this answer from this thread:
https://forums.beamdog.com/discussion/69160/mod-ascalons-questpack-kerzenburgforum/p6

**Comment by Gitjas** [comment]
Not sure what you are missing. From the "Readme-AC_QUEST-English.txt":

> 3 Jumper
> -------------------------
> An epic tale of honour, friendship and bunny-rabbits.
> 
> This component has two options: The first one is the original version, with Ugh and Jumper inside a cave west of south Beregost road.
> 
> The second one places them outside near the cave entrance. This is for compatibility reasons because TheArtisan's Shadow Magic mod also places a quest character into the cave. Install this component if you want to play both mods together.

I think that's pretty specific.

**Comment by Gitjas** [comment]
Ah, you meant in the GitHub readme. OK, will do.
