### ISSUE TITLE
Halfling Among the Eyeless Project Infinity Error

### ISSUE THREAD

**Issue by arosenow** [Gitjas/Ascalons_Questpack#15]
I seem to encounter an install error in project infinity when selecting Halfling among the eyeless. 
If I don't select this component then the install completes successfully, if i do select it, it returns a weidu error and requires a choice to abort or uninstall the mods in the PI gui

**Comment by Gitjas** [comment]
Please post your weidu.log contents, and also the DEBUG file with the error message. What game are you on?

**Comment by arosenow** [comment]
I realise now, it's not an error with this mod, it's an error I've previously reported to the Project Infinity git, the app sometimes reports mods as unsupported, although they are, and then produces this specific error during installation
