### ISSUE TITLE
Great Carlini not present at Lion Cross

### ISSUE THREAD

**Issue by Rataxor** [Gitjas/Ascalons_Questpack#6]
Hi,

I have an issue with the Great Carlini, he doesn't show up at the stone circle after I gave him the book, i try many times, just after delivering the book or few days later. Ge never was on the map were Gorion died.

I have many mods instal, my weidu is attached.

Thanks

[WeiDU.log](https://github.com/Gitjas/Ascalons_Questpack/files/10828872/WeiDU.log)

**Comment by Gitjas** [comment]
See here: https://www.gibberlings3.net/forums/topic/35182-please-note-you-need-to-edit-lions-way-area-script-or-take-xzar-in-party-temporarily-to-prevent-a-bug/

Will be fixed in the next version because I was too stupid for v4.3

**Comment by Gitjas** [comment]
Fixed in v4.4.
